### ISSUE TITLE
User.Identity.Name is null after 1.0.1 to 1.0.2 update

### ISSUE THREAD

**Issue by martinp-ccs** [auth0/auth0-aspnetcore-authentication#71] opened 2022-05-11 10:04 UTC
Within our .net 6 projects (including the MVC example project) when we have upgraded auth0 sdk wrapper from 1.0.1 to 1.0.2 the User.Identity.Name is now null and we can see these differences in the claims;

### 1.0.1 
`User.Identity.Claims[1] value = {name: ouruseremailaddress.email.com}`
`User.Identity.Name = "ouruseremailaddress.email.com"`
### 1.0.2 
`User.Identity.Claims[1] value = {http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name: ouruseremailaddress.email.com}`
`User.Identity.Name = null`

### Reproduction
Upgrade existing .NET Core 6 MVC projects Auth0 SDK nuget package from version 1.0.1 to 1.0.2

**Comment by frederikprijck** [comment] 2022-05-11 12:20
Thanks for reporting this. I managed to reproduce this, and it seems like the version of `Microsoft.IdentityModel.Protocols.OpenIdConnect`, specific for .NET 6, is doing different things with the `name` claim.

I managed to pin down the cause, and it appears to be cause by a bug that got reverted in https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/commit/d6f2b66d788195b50f2b1f700beb497851194c73. This fix appears to be released in https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/releases/tag/6.10.2

Did some testing and it seems to work when I ensure I am using that version.

Could you test if it works for you when u add a dependency on `Microsoft.IdentityModel.Protocols.OpenIdConnect` which is `>= 6.10.2`?

For our SDK, we only have a dependency on `Microsoft.AspNetCore.Authentication.OpenIdConnect`, however, [as you can see on Nuget](https://www.nuget.org/packages/Microsoft.AspNetCore.Authentication.OpenIdConnect), it has a dependency on `Microsoft.IdentityModel.Protocols.OpenIdConnect >= 6.10.0`, while we need 6.10.2

**Closed** 2022-05-11 14:44 UTC
Labels: bug report

**Comment by frederikprijck** [comment] 2022-05-12 15:49
This should be fixed in [1.0.3](https://github.com/auth0/auth0-aspnetcore-authentication/releases/tag/1.0.3)
