### ISSUE TITLE
User.Identity.Name is null

### ISSUE THREAD

**Issue by Socolin** [auth0/auth0-aspnetcore-authentication#58] opened 2022-01-17 19:29 UTC
Hello,

I've followed the steps in the tutorial https://auth0.com/docs/quickstart/webapp/aspnet-core/01-login and the field `User.Identity.Name` is `null`

This seems to come from https://github.com/auth0/auth0-aspnetcore-authentication/blob/main/src/Auth0.AspNetCore.Authentication/AuthenticationBuilderExtensions.cs#L72 
`NameClaimType` is set to `"name"` instead of default value / `ClaimTypes.Name`

Can you change this or make it configurable ?

**Comment by Socolin** [comment] 2022-01-17 19:37
I've found a way to configure it, could be nice to document it or add a field to `Auth0WebAppOptions`
```
services.Configure<OpenIdConnectOptions>(Auth0Constants.AuthenticationScheme,
options =>
{
	options.TokenValidationParameters.NameClaimType = ClaimTypes.Name;
});
```

**Comment by frederikprijck** [comment] 2022-01-18 08:11
@Socolin Can you elaborate on what makes this `null` for u ?
I tried reproducing this, but User.Identity.Name is not null for me:

![image](https://user-images.githubusercontent.com/2146903/149896069-a2af445e-5f47-4561-8249-690895f9d619.png)

 We are explicitly setting the `NameClaimType` because Auth0 requires this.
 
 The value of `ClaimTypes.Name` is `http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name.`, see https://docs.microsoft.com/en-us/dotnet/api/system.security.claims.claimtypes.name?view=net-6.0

However, Auth0 returns `name`, see:

![image](https://user-images.githubusercontent.com/2146903/149896717-4b150d65-17f2-4960-b57e-0aee1c23cada.png)

Are you perhaps trying to use this SDK with something other than Auth0?

**Comment by Socolin** [comment] 2022-01-18 14:51
I'm 100% certain to use it for Auth0.

There is no claim `name` in the list User.Claims: `http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name`

![image](https://user-images.githubusercontent.com/539620/149959537-efb16d09-9b4f-4d10-a6ec-5d81ed3244ef.png)

Here the code I'm using in Startup

```
services.AddAuth0WebAppAuthentication(options =>
{
options.Domain = Configuration["Authentication:Auth0:Domain"];
options.ClientId = Configuration["Authentication:Auth0:ClientId"];
});
// Workaround
services.Configure<OpenIdConnectOptions>(Auth0Constants.AuthenticationScheme,
options =>
{
	options.TokenValidationParameters.NameClaimType = ClaimTypes.Name;
});
```

```
...
app.UseAuthentication();
app.UseRouting();
app.UseAuthorization();
app.UseEndpoints(...
...
```

**Comment by frederikprijck** [comment] 2022-01-31 16:13
Closing, feel free to reopen if this continues to be an issue we should look into.

**Closed by frederikprijck** 2022-01-31 16:13 UTC
Labels: bug report

**Comment by Socolin** [comment] 2022-01-31 17:05
> Would you perhaps have any custom rule applied that removes the name claim and adds a new one ? By default, our ID Tokens use the `name` claim, see https://auth0.com/docs/secure/tokens/id-tokens/id-token-structure.

I did not find any custom configuration about this in our code, but it's maybe hidden in one of the extension methods. 

If it's working for newly created project with the example there is no need to change, and since I was able to override the configuration with the workaround and it's working fine for me, I'm not going to dig more about this. This can stay closed.
